setup:
  @if ! [[ -d .git ]]; then git init; fi
  pdm install --dev
  pdm run pre-commit install --install-hooks

update:
  pdm sync
  pdm update
  pdm run pre-commit install-hooks
  pdm run pre-commit autoupdate

fmt:
  pdm run pre-commit run black --all-files
  pdm run pre-commit run blacken-docs --all-files
  pdm run pre-commit run isort --all-files

ruff:
  pdm run pre-commit run ruff --all-files

typecheck:
  pdm run mypy src

audit:
  pdm run pre-commit run pip-audit

lint: ruff typecheck

check-commits:
  pdm run cz check --rev-range origin/main..HEAD

check-version:
  pdm run cz bump --check-consistency --dry-run

pre-release: fmt audit lint check-commits check-version

test:
  pdm run pytest --cov=src/grader --cov-report=term-missing --cov-report=html

export:
  pdm export --prod -f=requirements.txt

preview-docs:
  pdm run mike serve --config-file=docs/mkdocs.yml

release: pre-release
  pdm run cz bump
  git push
  git push --tag

alias bump := release
