name: Create Release

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  release-create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}" # access a private repo
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # required
          branch: main                                # accept only main branch
